name = "myitem"
compatibility_date = "2025-09-01"
pages_build_output_dir = "public"

# For local development / Workers
[[d1_databases]]
binding = "DB"
database_name = "myitem-db"
database_id = "6d578ae1-ff99-45fb-80b2-d0c486c8356f"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "myitem-images"

# Optional: for full Worker if you prefer instead of Pages Functions
# main = "src/worker.js"
